"""Map verbose Wikidata POS labels to short WN-LMF POS codes."""
from wn.constants import (
    ADJ,
    ADP,
    ADV,
    CONJ,
    DET,
    INTERROGATIVE,
    INTJ,
    NOUN,
    NUM,
    OTHER,
    PART,
    PHRASE,
    PRON,
    VERB,
)

# Content POS codes: those that omw-en covers natively. Used to decide
# whether a SKIP_POS-classified Wikidata lemma should still be included
# because omw-en doesn't have it under that POS.
CONTENT_TARGETS = frozenset({NOUN, VERB, ADJ, ADV})

POS_MAP: dict[str, str] = {
    # --- Pronoun (h) ---
    "pronoun": PRON,
    "personal pronoun": PRON,
    "possessive determiner": PRON,
    "reflexive personal pronoun": PRON,
    "reflexive pronoun": PRON,
    "reciprocal pronoun": PRON,
    "interrogative pronoun": PRON,
    "indefinite pronoun": PRON,
    "relative pronoun": PRON,
    "demonstrative pronoun": PRON,
    "definite pronoun": PRON,
    "pronominal locution": PRON,
    "possessive pronoun": PRON,
    "subject pronoun": PRON,
    "object pronoun": PRON,
    "resumptive pronoun": PRON,
    "distributive pronoun": PRON,
    "determinative pronoun": PRON,
    "pro-form": PRON,
    # --- Determiner (d) ---
    "determiner": DET,
    "definite article": DET,
    "indefinite article": DET,
    "demonstrative determiner": DET,
    "definite determiner": DET,
    "indefinite determiner": DET,
    "interrogative determinant": DET,
    "demonstrative": DET,
    "article": DET,
    "quantifier": DET,
    "partitive": DET,
    # --- Noun (n) ---
    "noun": NOUN,
    "proper noun": NOUN,
    "common noun": NOUN,
    "abstract noun": NOUN,
    "compound noun": NOUN,
    "count noun": NOUN,
    "mass noun": NOUN,
    "personal noun": NOUN,
    "agent noun": NOUN,
    "locative noun": NOUN,
    "indeclinable noun": NOUN,
    "verbal noun": NOUN,
    "plurale tantum": NOUN,
    "noun class": NOUN,
    "nominal": NOUN,
    "name": NOUN,
    "given name": NOUN,
    "family name": NOUN,
    "location": NOUN,
    "jukugo": NOUN,  # Japanese kanji compound noun
    # --- Verb (v) ---
    "verb": VERB,
    "proper verb": VERB,
    "phrasal verb": VERB,
    "auxiliary verb": VERB,
    "japanese auxiliary verb": VERB,
    "passive verb": VERB,
    "nominalized verb": VERB,
    "copula": VERB,
    "preverb": VERB,
    "verbaliser": VERB,
    "participle": VERB,
    "present participle": VERB,
    "gerund": VERB,
    "transgressive": VERB,
    "converb": VERB,
    "past tense": VERB,
    "imperative form": VERB,
    "infinitive": VERB,
    # --- Adjective (a) ---
    "adjective": ADJ,
    "satellite adjective": ADJ,
    "proper adjective": ADJ,
    "prenominal adjective": ADJ,
    "adnominal adjective": ADJ,
    "na-adjective": ADJ,
    "true adjective": ADJ,
    "demonstrative adjective": ADJ,
    "possessive adjective": ADJ,
    "relative adjective": ADJ,
    "reflexive adjective": ADJ,
    "reflexive possessive adjective": ADJ,
    "indefinite adjective": ADJ,
    "numeral adjective": ADJ,
    "pronominal adjective": ADJ,
    "interrogative adjective": ADJ,
    "predicative": ADJ,
    "nominal modifier": ADJ,
    # --- Adverb (r) ---
    "adverb": ADV,
    "adverbial phrase": ADV,
    "adverbial locution": ADV,
    "adverbial particle": ADV,
    "interrogative adverb": ADV,
    "prepositional adverb": ADV,
    "postpositive adverb": ADV,
    "demonstrative adverb": ADV,
    "modal adverb": ADV,
    "correlative adverb": ADV,
    "pronominal adverb": ADV,
    "predicative adverb": ADV,
    "intensifier": ADV,
    "adverbial modifier": ADV,
    "verbal modifier": ADV,
    # --- Adposition (p) ---
    "preposition": ADP,
    "prepositional locution": ADP,
    "postposition": ADP,
    "ambiposition": ADP,
    "adposition": ADP,
    "localiser": ADP,
    # --- Conjunction (c) ---
    "conjunction": CONJ,
    "coordinating conjunction": CONJ,
    "subordinating conjunction": CONJ,
    "concessive conjunction": CONJ,
    "complementizer": CONJ,
    "linker": CONJ,
    "adversative linker": CONJ,
    # --- Numeral (m) ---
    "numeral": NUM,
    "number": NUM,
    "digit": NUM,
    "ordinal numeral": NUM,
    "classifier": NUM,
    "chinese classifier": NUM,
    "japanese counter word": NUM,
    "measure word": NUM,
    # --- Interjection (i) ---
    "interjection": INTJ,
    "idiomatic interjection": INTJ,
    "greeting": INTJ,
    # --- Interrogative (q) ---
    "interrogative word": INTERROGATIVE,
    "interrogative expression": INTERROGATIVE,
    "interrogative": INTERROGATIVE,
    "question": INTERROGATIVE,
    "question tag": INTERROGATIVE,
    # --- Particle (y) ---
    "grammatical particle": PART,
    "infinitive marker": PART,
    "modal particle": PART,
    "negative particle": PART,
    "emphatic particle": PART,
    "vocative particle": PART,
    "allocutive particle": PART,
    "interrogative particle": PART,
    "verbal particle": PART,
    "japanese particle": PART,
    "助字": PART,  # Japanese for "auxiliary character" — grammatical particle
    "clitic": PART,
    "enclitic": PART,
    "proclitic": PART,
    "mesoclitic": PART,
    "object marker": PART,
    "proper noun marker": PART,
    "honorific particle": PART,
    "exceptive particle": PART,
    # --- Phrase (t) ---
    "phraseme": PHRASE,
    "established collocation": PHRASE,
    "fixed expression": PHRASE,
    "latin phrase": PHRASE,
    "infinitive phrase": PHRASE,
    "verbal expression": PHRASE,
    "popular saying": PHRASE,
    "locution": PHRASE,
    "postpositive locution": PHRASE,
    "copulative locution": PHRASE,
    "simile": PHRASE,
    # --- Other (x) ---
    # acronym/abbreviation, sub-word affixes, and labels that don't map
    # cleanly onto a single POS all fall through to OTHER via the
    # POS_MAP.get(..., OTHER) default in create_extensions.py /
    # the normalizer. Listed explicitly only when present in input.
    "acronym": OTHER,
    "abbreviation": OTHER,
}

CONTENT_POS_MAP: dict[str, str] = {
    label: code for label, code in POS_MAP.items() if code in CONTENT_TARGETS
}
